extends Node
@warning_ignore("unused_signal")
signal wind_changed(current_wind:int)
@warning_ignore("unused_signal")
signal moving_pathfinding_objects()
@warning_ignore("unused_signal")
signal wind_mode(wind_option:String)
@warning_ignore("unused_signal")
signal all_enemies_dead()
@warning_ignore("unused_signal")
signal enemy_has_died(enemy)